// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void insuranceTrackerage25DExp3accidents0() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Smit Dharmesh");
    driver.FindElement(By.Id("lastName")).SendKeys("Mehta");
    driver.FindElement(By.Id("address")).SendKeys("280 philip street");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3X1");
    driver.FindElement(By.Id("phone")).SendKeys("2898892480");
    driver.FindElement(By.Id("email")).SendKeys("smitmehta.work@gmail.com");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("289-889-2480");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("$2500"));
    }
  }
  [Test]
  public void insuranceTrackerDrivingExperiencemorethanage() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Radha");
    driver.FindElement(By.Id("lastName")).SendKeys("coco");
    driver.FindElement(By.Id("address")).SendKeys("dubai street");
    driver.FindElement(By.Id("city")).SendKeys("london");
    driver.FindElement(By.Id("postalCode")).SendKeys("L3E 3U8");
    driver.FindElement(By.Id("phone")).SendKeys("232-535-2352");
    driver.FindElement(By.Id("email")).SendKeys("cocoradha@melon.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("65");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("66");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("2");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("No Insurance for you!! Driver Age / Experience Not Correct"));
    }
  }
  [Test]
  public void insuranceTrackerNegativenumberinDrivingExperience() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Jack");
    driver.FindElement(By.Id("lastName")).SendKeys("li");
    driver.FindElement(By.Id("address")).SendKeys("near conestoga mall");
    driver.FindElement(By.Id("city")).SendKeys("waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("n2l 5t6");
    driver.FindElement(By.Id("phone")).SendKeys("987-098-3748");
    driver.FindElement(By.Id("email")).SendKeys("jackli@google.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("44");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("-4");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 0."));
  }
  [Test]
  public void insuranceTrackerage25DExp3accidents4() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.LinkText("prog8170a04/")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("krupa");
    driver.FindElement(By.Id("lastName")).SendKeys("s");
    driver.FindElement(By.Id("address")).SendKeys("some street");
    driver.FindElement(By.Id("city")).SendKeys("kitchner");
    driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3h1");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("999-999-3232");
    driver.FindElement(By.Id("email")).SendKeys("myemail@hotmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("4");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
    }
  }
  [Test]
  public void insuranceTrackerage27DExp3accidents0() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("raj");
    driver.FindElement(By.Id("lastName")).SendKeys("vyas");
    driver.FindElement(By.Id("address")).SendKeys("oyther street");
    driver.FindElement(By.Id("city")).SendKeys("waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("n2g 4f4");
    driver.FindElement(By.Id("phone")).SendKeys("1232424242");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("wrongemail@email.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("27");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      var element = driver.FindElement(By.Id("btnSubmit"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
  }
  [Test]
  public void insuranceTrackerage28DExp3accidents0InvalidEmail() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Dongpeng");
    driver.FindElement(By.Id("lastName")).SendKeys("Dai");
    driver.FindElement(By.Id("address")).SendKeys("weber street");
    driver.FindElement(By.Id("city")).SendKeys("waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("n3l 4x2");
    driver.FindElement(By.Id("phone")).SendKeys("098-293-2833");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("dongpengdaiconestoga.com");
    driver.FindElement(By.Id("age")).SendKeys("28");
    driver.FindElement(By.Id("experience")).SendKeys("3");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
  }
  [Test]
  public void insuranceTrackerage35DExp10accidents2() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("seongjun");
    driver.FindElement(By.Id("lastName")).SendKeys("choi");
    driver.FindElement(By.Id("address")).SendKeys("different street");
    driver.FindElement(By.Id("city")).SendKeys("kitchner");
    driver.FindElement(By.Id("postalCode")).SendKeys("n2w 4r2");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("123-232-4353");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).SendKeys("anotheremil@gmail.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("2");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("$1350"));
    }
  }
  [Test]
  public void insuranceTrackerage35DExp17accidents1InvalidPostal() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Iulia");
    driver.FindElement(By.Id("lastName")).SendKeys("Danilov");
    driver.FindElement(By.Id("address")).SendKeys("central station");
    driver.FindElement(By.Id("city")).SendKeys("Kitchener");
    driver.FindElement(By.Id("phone")).SendKeys("898-222-1123");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2Jww2");
    driver.FindElement(By.Id("email")).SendKeys("igotjob@agfa.com");
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("experience")).SendKeys("17");
    driver.FindElement(By.Id("accidents")).SendKeys("1");
    driver.FindElement(By.Id("btnSubmit")).Click();
    Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
  }
  [Test]
  public void insuranceTrackerage37DExp8accidentsOmmited() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("vidhi");
    driver.FindElement(By.Id("lastName")).SendKeys("kapadiya");
    driver.FindElement(By.Id("address")).SendKeys("krupa st.");
    driver.FindElement(By.Id("city")).SendKeys("kitchner");
    driver.FindElement(By.Id("postalCode")).SendKeys("n3s 5f3");
    driver.FindElement(By.Id("phone")).SendKeys("473-343-2525");
    driver.FindElement(By.Id("email")).SendKeys("vidhinulaptopsaras@hp.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("37");
    driver.FindElement(By.Id("experience")).SendKeys("8");
    driver.FindElement(By.Id("btnSubmit")).Click();
    Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
  }
  [Test]
  public void insuranceTrackerage45DExpOmittedaccidents0() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Smit Dharmesh");
    driver.FindElement(By.Id("lastName")).SendKeys("Mehta");
    driver.FindElement(By.Id("address")).SendKeys("280 philip street");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3X1");
    driver.FindElement(By.Id("email")).SendKeys("smitmehta.work@gmail.com");
    driver.FindElement(By.Id("phone")).SendKeys("289-889-2480");
    driver.FindElement(By.Id("age")).SendKeys("45");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
  }
  [Test]
  public void insuranceTrackerage72DExp3accidents10() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("oscar");
    driver.FindElement(By.Id("lastName")).SendKeys("pinzon");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("conestoga college");
    driver.FindElement(By.Id("city")).SendKeys("waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("n2j 2e2");
    driver.FindElement(By.Id("phone")).SendKeys("232-535-2352");
    driver.FindElement(By.Id("email")).SendKeys("bestwebdev@irock.com");
    driver.FindElement(By.Id("age")).SendKeys("27");
    driver.FindElement(By.Id("experience")).SendKeys("10");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("2");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("$1800"));
    }
  }
  [Test]
  public void insuranceTrackerageOmittedDExp5accidents0() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("raj");
    driver.FindElement(By.Id("lastName")).SendKeys("truvedi");
    driver.FindElement(By.Id("address")).SendKeys("albert ave.");
    driver.FindElement(By.Id("city")).SendKeys("waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("n2i 4r3");
    driver.FindElement(By.Id("phone")).SendKeys("222-332-3353");
    driver.FindElement(By.Id("email")).SendKeys("rtrivedi@uwaterloo.ca");
    driver.FindElement(By.Id("experience")).SendKeys("5");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
  }
  [Test]
  public void insuranceTrackeragelessthan16() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("jose");
    driver.FindElement(By.Id("lastName")).SendKeys("martinez");
    driver.FindElement(By.Id("address")).SendKeys("other st.");
    driver.FindElement(By.Id("city")).SendKeys("waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("f2t 4f4");
    driver.FindElement(By.Id("phone")).SendKeys("123-546-6424");
    driver.FindElement(By.Id("email")).SendKeys("ihavekids@old.com");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("15");
    driver.FindElement(By.Id("experience")).SendKeys("0");
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      var element = driver.FindElement(By.Id("btnSubmit"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
  }
  [Test]
  public void insuranceTrackerdifferencebetweenageandexperiencegreaterthanorequalto16() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("ayush");
    driver.FindElement(By.Id("lastName")).SendKeys("subedi");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("280 philip street");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("N2L 3X1");
    driver.FindElement(By.Id("phone")).SendKeys("2898892480");
    driver.FindElement(By.Id("email")).SendKeys("smitmehta.work@gmail.com");
    driver.FindElement(By.Id("phone")).Click();
    driver.FindElement(By.Id("phone")).SendKeys("289-889-2480");
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("30");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("16");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("No Insurance for you!! Driver Age / Experience Not Correct"));
    }
  }
  [Test]
  public void insuranceTrackerage25DExp0accidents0Output4000() {
    driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 875);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("JianXian");
    driver.FindElement(By.Id("lastName")).SendKeys("Li");
    driver.FindElement(By.Id("address")).SendKeys("we");
    driver.FindElement(By.Id("city")).SendKeys("Waterloo");
    driver.FindElement(By.Id("postalCode")).SendKeys("J2L 3X1");
    driver.FindElement(By.Id("phone")).SendKeys("442-424-4244");
    driver.FindElement(By.Id("email")).SendKeys("JianXianLi@tiger.com");
    driver.FindElement(By.Id("email")).Click();
    driver.FindElement(By.Id("email")).Click();
    {
      var element = driver.FindElement(By.Id("email"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("25");
    driver.FindElement(By.Id("experience")).Click();
    driver.FindElement(By.Id("experience")).SendKeys("0");
    driver.FindElement(By.Id("accidents")).Click();
    driver.FindElement(By.Id("accidents")).SendKeys("0");
    driver.FindElement(By.Id("btnSubmit")).Click();
    {
      string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("$4000"));
    }
  }
}
